[program:hoard_gunicorn]
command=/home/mbi/Code/hoard/.venv/bin/gunicorn hoard.wsgi:application -c /home/mbi/Code/hoard/conf/prod/gunicorn.conf.py
process_name = hoard_gunicorn
directory = /home/mbi/Code/hoard/hoard
user = hoard
autostart = true
autorestart = true
startsecs = 5

environment=HOME=/home/projects/hoard,TMPDIR=/home/mbi/Code/hoard/tmp

redirect_stderr = true
stdout_logfile = /home/mbi/Code/hoard/logs/gunicorn.stdout.log
stdout_logfile_maxbytes = 1048576
stdout_logfile_backups = 10
