# Generated by Django 6.1.1 on 2026-09-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hoarder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="preprocessors",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Dotted paths of functions applied to the payload before storage. Each function takes a dict and returns a dict.",
            ),
        ),
    ]
