# Generated by Django 6.1.1 on 2026-09-18 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hoarder", "0002_category_preprocessors"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hoard",
            options={"ordering": ["-recorded"]},
        ),
    ]
